name: mentro_ai_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  country_picker: any
  image_picker: ^1.1.2
  just_audio: ^0.9.40

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

# ── Launcher icon config — flutter: se BAHAR ──────────────
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/applogo.png"

# ── Flutter section ────────────────────────────────────────
flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/fonts/

  fonts:
    - family: poppin
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: poppinbold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: inter
      fonts:
        - asset: assets/fonts/Inter_18pt-Regular.ttf
    - family: manrope
      fonts:
        - asset: assets/fonts/Manrope-Light.ttf
    - family: montserrat
      fonts:
        - asset: assets/fonts/Montserrat-SemiBold.ttf